b2b/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

from cms.sitemaps import CMSSitemap
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.static import serve

admin.autodiscover()

urlpatterns = [
    url(r'^sitemap\.xml$', sitemap,
        {'sitemaps': {'cmspages': CMSSitemap}}),
]

urlpatterns += i18n_patterns(
    url(r'^admin/', include(admin.site.urls)),  # NOQA
    url(r'^', include('cms.urls')),
)

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns = [
        url(r'^media/(?P<path>.*)$', serve,
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        ] + staticfiles_urlpatterns() + urlpatterns

company/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$',
        views.CompaniesList.as_view(),
        name='list'),
    url(r'^created-by-user$', views.UserCompanies.as_view(),
        name='created-by-user'),
    url(r'^register$', views.CompanyRegister.as_view(), name='register'),
    url(r'^update/(?P<pk>\d+)/step-2$', views.company_data_update,
        name='step_2'),
    url(r'^update/(?P<pk>\d+)$', views.CompanyUpdate.as_view(), name='update'),
    url(r'^delete/(?P<pk>\d+)$', views.CompanyDelete.as_view(), name='delete'),
    url(r'^(?P<pk>\d+)$', views.CompanyDetail.as_view(), name='detail'),
    url(r'^(?P<category>[\w-]+)$', views.CompaniesList.as_view(),
        name='category'),
    url(r'^gallery/(\d+)$', views.get_gallery_src, name='gallery'),
    url(r'^gallery/all$', views.get_gallery_src, name='full_gallery'),
]

company/models.py
from datetime import datetime
from random import random

from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, RegexValidator
from django.db import models
from django.utils.translation import ugettext_lazy as _


class Category(models.Model):
    name = models.CharField(_('name'), max_length=50)
    slug = models.SlugField(_('slug'), max_length=20)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('category')
        verbose_name_plural = _('categories')


class CompanyManager(models.Manager):
    def get_queryset(self):
        return super(CompanyManager, self).get_queryset().filter(active=True)

    def get_all(self):
        return super(CompanyManager, self).get_queryset()


class Company(models.Model):
    objects = CompanyManager()

    active = models.BooleanField(default=False)
    created_by = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name=_('created by'),
        help_text=_('The uploader of the company'),
    )

    def _generate_filename(self, filename):
        return 'company_{}/logo/{}'.format(self.id, filename)

    logo = models.ImageField(
        upload_to=_generate_filename,
        verbose_name=_('logotype'),
        help_text=_('Add company logotype'),
    )
    name = models.CharField(
        _('company name'),
        max_length=50,
        unique=True,
        help_text=_('Name of the company'),
    )
    foundation_year = models.PositiveSmallIntegerField(
        _('foundation year'),
        validators=[
            MaxValueValidator(
                limit_value=datetime.now().year,
                message=_("You can't register not yet existing company"),
            ),
        ],
        help_text=_('Year of Foundation'),
    )
    category = models.ManyToManyField(
        Category,
        verbose_name=_('category'),
        help_text=_(
            'Category of enterprises by types of products (no more than three)',
        ),
    )

    overview = models.TextField(
        verbose_name=_('overview'),
        max_length=2000,
        help_text=_(
            '''Duration and experience, the description of the company,
            products'''
        ),
    )
    USREOU = models.BigIntegerField(
        verbose_name=_('USREOU'),
        unique=True,
        validators=[
            RegexValidator(
                regex=r'^\d{7,12}$',
                message=_('USREOU code consists of minimum 7 digits, '
                          'a maximum of 12 digits'),
            ),
        ],
        help_text=_('USREOU'),
    )
    address = models.CharField(
        _('address'),
        max_length=20,
        help_text=_('Business address'),
    )
    fax = models.CharField(
        _('fax'),
        max_length=20,
        blank=True,
        help_text=_('Enterprise fax'),
    )
    web_site = models.URLField(
        _('web site'),
        blank=True,
        help_text=_('Company website'),
    )
    additionalInfo = models.ManyToManyField(
        'AdditionalInfo',
        blank=True,
        verbose_name=_('additional information'),
        help_text=_('Additional information about the company'),
    )

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        from django.core.urlresolvers import reverse

        return reverse('companies:detail', kwargs={'pk': self.pk})

    class Meta:
        verbose_name = _('company')
        verbose_name_plural = _('companies')


class Phone(models.Model):
    company = models.ForeignKey(Company,
                                on_delete=models.CASCADE,
                                verbose_name=_('company'))
    phone = models.IntegerField(_('phone'), help_text=_('Phone'))

    def __str__(self):
        return str(self.phone)

    class Meta:
        verbose_name = _('phone')
        verbose_name_plural = _('phones')


class Email(models.Model):
    company = models.ForeignKey(Company,
                                on_delete=models.CASCADE,
                                verbose_name=_('company'))
    email = models.EmailField(_('email'), help_text=_('email'))

    def __str__(self):
        return str(self.email)

    class Meta:
        verbose_name = _('email')
        verbose_name_plural = _('emails')


class Photo(models.Model):
    def _generate_filename(self, filename):
        dt = datetime.now().strftime('%d.%m.%Y %H-%M-%S')
        rnd = random()
        return 'company_{}/{}/{}/{}'.format(self.company.id, dt, rnd, filename)

    company = models.ForeignKey(
        Company,
        on_delete=models.CASCADE,
        verbose_name=_('company'),
    )
    product = models.CharField(
        _('product'),
        max_length=50,
        help_text=_('Product on image. Please, select different products.'),
    )
    image = models.ImageField(
        upload_to=_generate_filename,
        verbose_name=_('photo'),
        help_text=_('Sample products'),
    )
    pub_date = models.DateField(auto_now=True, blank=True, null=True)

    def __str__(self):
        return str(self.image)

    class Meta:
        verbose_name = _('photo')
        verbose_name_plural = _('photos')


class AdditionalInfo(models.Model):
    info = models.CharField(
        _('additional information'),
        max_length=30,
        help_text=_('Additional information about the company'),
    )

    def __str__(self):
        return self.info

    class Meta:
        verbose_name = _('additional information about the company')
        verbose_name_plural = _('additional information about the company')

company/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from .models import Company, Email, Phone, Photo

attrs = {
    'logo': {'class': 'form-control'},
    'name': {'class': 'form-control', 'required': 'required'},
    'foundation_year': {'class': 'form-control', 'required': 'required'},
    'category': {},
    'overview': {'class': 'form-control', 'required': 'required'},
    'USREOU': {'class': 'form-control', 'required': 'required'},
    'address': {'class': 'form-control', 'required': 'required'},
    'fax': {'class': 'form-control'},
    'web_site': {'class': 'form-control'},
    'additionalInfo': {},
}


class CompanyForm(forms.ModelForm):
    class Meta:
        model = Company
        exclude = ('active', 'created_by')
        localized_fields = '__all__'
        widgets = {
            'logo': forms.ClearableFileInput(attrs=attrs['logo']),
            'name': forms.TextInput(attrs=attrs['name']),
            'foundation_year': forms.NumberInput(
                attrs=attrs['foundation_year'],
            ),
            'category': forms.CheckboxSelectMultiple(attrs=attrs['category']),
            'overview': forms.Textarea(attrs=attrs['overview']),
            'USREOU': forms.NumberInput(attrs=attrs['USREOU']),
            'address': forms.TextInput(attrs=attrs['address']),
            'fax': forms.TextInput(attrs=attrs['fax']),
            'web_site': forms.URLInput(attrs=attrs['web_site']),
            'additionalInfo': forms.CheckboxSelectMultiple(
                attrs=attrs['additionalInfo'],
            ),
        }

    def clean_category(self):
        category = self.cleaned_data['category']
        if 1 > len(category) > 3:
            raise forms.ValidationError(_('Please, select from 1 to 3 '
                                          'categories'))

        return category

    def clean_USREOU(self):
        USREOU = self.cleaned_data['USREOU']
        if 7 > len(str(USREOU)) > 12:
            raise forms.ValidationError(
                _('USREOU code must be consists of minimum 7 digits, '
                  'a maximum of 12 digits'),
            )

        return USREOU


params = {
    'Phone': {
        'fields': ('phone',),
        'widgets': {
            'phone': forms.NumberInput(attrs={'class': 'form-control'}),
        },
    },
    'Email': {
        'fields': ('email',),
        'widgets': {
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
        }
    },
    'Photo': {
        'fields': ('product', 'image'),
        'widgets': {
            'product': forms.TextInput(attrs={'class': 'form-control'}),
            'image': forms.ClearableFileInput(attrs={'class': 'form-control'}),
        }
    },
}

PhoneInline = forms.inlineformset_factory(
    Company, Phone,
    **params['Phone'],
    extra=3,
    max_num=3, validate_max=True,
    min_num=1, validate_min=True,
)
EmailInline = forms.inlineformset_factory(
    Company, Email,
    **params['Email'],
    extra=3,
    max_num=3, validate_max=True,
    min_num=1, validate_min=True,
)
PhotoInline = forms.inlineformset_factory(
    Company, Photo,
    **params['Photo'],
    extra=10,
    max_num=10, validate_max=True,
)

company/views.py
import math

from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.core.urlresolvers import reverse_lazy
from django.db.models import Q
from django.http import Http404
from django.shortcuts import get_object_or_404, render, redirect
from django.utils.decorators import method_decorator
from django.utils.translation import ugettext as _
from django.views import generic
from django_ajax.decorators import ajax

from . import forms
from .models import Category, Company, Photo


class CompaniesList(generic.ListView):
    context_object_name = 'companies_list'

    def get_queryset(self):
        query = self.request.GET.get('search')
        category = self.kwargs.get('category')
        self.has_category_list = True
        if query is not None:
            # search
            self.has_category_list = False
            return Company.objects.filter(
                Q(name__icontains=query) |
                Q(overview__icontains=query) |
                Q(address__icontains=query) |
                Q(photo__product__icontains=query)
            ).distinct()
        elif category is None:
            # all companies
            return Company.objects.all()
        else:
            # companies by category
            category_obj = get_object_or_404(Category, slug=category)
            return Company.objects.filter(category=category_obj)

    def get_context_data(self, **kwargs):
        context = super(CompaniesList, self).get_context_data(**kwargs)
        context['active_category'] = self.kwargs.get('category')
        if self.has_category_list:
            context['categories'] = chunks(Category.objects.all(), 3)
        return context


def chunks(lst, chunk_count):
    chunk_size = int(math.ceil(len(lst) / chunk_count))
    return [lst[i:i + chunk_size] for i in range(0, len(lst), chunk_size)]


class UserCompanies(generic.ListView):
    context_object_name = 'companies_list'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(UserCompanies, self).dispatch(*args, **kwargs)

    def get_queryset(self):
        return Company.objects.filter(created_by=self.request.user)

    def get_context_data(self, **kwargs):
        context = super(UserCompanies, self).get_context_data(**kwargs)
        context['created_by_user'] = True
        return context


class CompanyDetail(generic.DetailView):
    model = Company
    context_object_name = 'company'

    def get_context_data(self, **kwargs):
        context = super(CompanyDetail, self).get_context_data(**kwargs)

        # Add to context verbose names of all Company fields.
        for field in Company._meta.fields:
            context[field.attname] = field.verbose_name

        return context


class CompanyRegister(generic.edit.CreateView):
    model = Company
    template_name = 'company/company_form_1.html'
    form_class = forms.CompanyForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(CompanyRegister, self).dispatch(*args, **kwargs)

    def form_valid(self, form):
        company = form.save(commit=False)
        company.created_by = self.request.user
        company.save()
        company.category = form.cleaned_data.get('category')
        company.additionalInfo = form.cleaned_data.get('additionalInfo')
        company.save()

        return redirect(reverse_lazy('companies:step_2',
                                     kwargs={'pk': company.pk}))

    def get_context_data(self, **kwargs):
        context = super(CompanyRegister, self).get_context_data(**kwargs)
        context['submit_text'] = _('Register')
        return context


class CompanyUpdate(generic.edit.UpdateView):
    model = Company
    template_name = 'company/company_form_1.html'
    form_class = forms.CompanyForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        company = get_object_or_404(Company, pk=self.kwargs.get('pk'))
        if company.created_by != self.request.user:
            return redirect('/')
        else:
            return super(CompanyUpdate, self).dispatch(*args, **kwargs)

    def get_success_url(self):
        return reverse_lazy('companies:step_2',
                            kwargs={'pk':self.kwargs.get('pk')})

    def get_context_data(self, **kwargs):
        context = super(CompanyUpdate, self).get_context_data(**kwargs)
        context['submit_text'] = _('Next')
        return context


@login_required
def company_data_update(request, pk):
    try:
        company = Company.objects.get_all().get(pk=pk)
    except ObjectDoesNotExist:
        raise Http404()

    if not company.active:
        company.active = True
        company.save()

    if request.user != company.created_by:
        return redirect(reverse_lazy('companies:created-by-user'))

    if request.method == 'GET':
        phone_formset = forms.PhoneInline(instance=company, prefix='phone')
        email_formset = forms.EmailInline(instance=company, prefix='email')
        photo_formset = forms.PhotoInline(instance=company, prefix='photo')
        return render(
            request,
            'company/company_form_2.html',
            {
                'phone_formset': phone_formset,
                'email_formset': email_formset,
                'photo_formset': photo_formset,
                'submit_text': _('Update'),
            },
        )
    elif request.method == 'POST':
        formsets = (
            forms.PhoneInline(request.POST,
                              instance=company,
                              prefix='phone'),
            forms.EmailInline(request.POST,
                              instance=company,
                              prefix='email'),
            forms.PhotoInline(request.POST, request.FILES,
                              instance=company,
                              prefix='photo'),
        )
        if all(formset.is_valid() for formset in formsets):
            for formset in formsets:
                formset.instance = company
                formset.save()

            return redirect(reverse_lazy('companies:created-by-user'))
        else:
            return render(
                request,
                'company/company_form_2.html',
                {
                    'phone_formset': formsets[0],
                    'email_formset': formsets[1],
                    'photo_formset': formsets[2],
                    'submit_text': _('Update'),
                },
            )


class CompanyDelete(generic.edit.DeleteView):
    model = Company
    success_url = reverse_lazy('companies:created-by-user')


@ajax
def get_gallery_src(request, category_id=None):
    if category_id is None:
        gallery = Photo.objects.order_by('-pub_date')[:10]
    else:
        # This is one query.
        gallery = Photo.objects.filter(company__category__id=int(category_id))
        gallery = gallery.order_by('-pub_date')[:10]
    return render(request, 'company/gallery.html', {'gallery': gallery})

company/templates/company/company_confirm_delete.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <p>{% trans 'Are you sure you want to delete' %} "{{ object }}"?</p>
        <input type="submit" value="Confirm" />
    </form>
{% endblock content %}

company/templates/company/company_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load i18n %}

{% block content %}
  <div class="company-info">
    <div class="row">
      <div class="logo col-md-6">
        <img src="{% thumbnail company.logo 75x75 crop %}" alt="logo">
      </div>
      <div class="year col-md-6 text-right">
        {{ company.foundation_year }} p.
      </div>
    </div>
    
    <div class="row">
      <div class="col-md-3">
        <b>{{ name }}:</b>
      </div>
      <div class="col-md-9">{{ company.name }}</div>
    </div>
    
    <div class="row">
      <div class="col-md-3"><b>{{ USREOU }}:</b></div>
      <div class="col-md-9">{{ company.USREOU }}</div>
    </div>
    <div class="row">
      <div class="col-md-3"><b>{{ address }}:</b></div>
      <div class="col-md-9">{{ company.address }}</div>
    </div>
    <div class="row">
      <div class="col-md-3"><b>Телефони:</b></div>
      <div class="col-md-9">
        {% for phone in company.phone_set.all %}
          <div>{{ phone }}</div>
        {% endfor %}
      </div>
    </div>
    {% if company.fax %}
      <div class="row">
        <div class="col-md-3"><b>{{ fax }}:</b></div>
        <div class="col-md-9">{{ company.fax }}</div>
      </div>
    {% endif %}
    <div class="row">
      <div class="col-md-3"><b>Emails:</b></div>
      <div class="col-md-9">
        {% for email in company.email_set.all %}
          <div>{{ email }}</div>
        {% endfor %}
      </div>
    </div>
    {% if company.web_site %}
      <div class="row">
        <div class="col-md-3"><b>{{ web_site }}:</b></div>
        <div class="col-md-9">{{ company.web_site }}</div>
      </div>
    {% endif %}    
    <div class="row">
      <div class="col-md-3">
        <b>{{ overview }}:</b>
      </div>
      <div class="col-md-9">{{ company.overview }}</div>
    </div>

    <div class="row">
      <div class="col-md-3">
        <b>{% trans 'Scope of activity:' %}</b>
      </div>
      <div class="col-md-9">
        {% for category in company.category.all %}
          <a href="{% url 'companies:category' category=category.slug %}" class="btn btn-default">
            {{ category }}
          </a>
        {% endfor %}  
      </div>
    </div>
    {% if company.additionalInfo.all %}
      <div class="row">
        <div class="col-md-3"><b>{% trans 'Additional information about the company:' %}</b></div>
        <div class="col-md-9">
          {% for additional_info in company.additionalInfo.all %}
            <div>{{ additional_info }}</div>
          {% endfor %}
        </div>
      </div>
    {% endif %}
  </div>

    {% if company.photo_set.all %}
        {% include 'company/gallery.html' with gallery=company.photo_set.all %}
    {% endif %}

{% endblock content %}

company/templates/company/company_form_1.html
{% extends 'base.html' %}

{% block content %}
  <div class="col-md-offset-3 col-md-6">
    <form action="{{ request.path }}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'form.html' %}
        <div class="form-group">
            <input type="submit" class="btn btn-info form-control" value="{{ submit_text }}">
        </div>
    </form>
    </div>
{% endblock content %}

company/templates/company/company_form_2.html
{% extends 'base.html' %}

{% block content %}
  <div class="col-md-offset-3 col-md-6">
    <form action="{{ request.path }}" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        {{ phone_formset.management_form }}
        {% for form in phone_formset %}
            {% include 'form.html' %}
        {% endfor %}

        {{ email_formset.management_form }}
        {% for form in email_formset %}
            {% include 'form.html' %}
        {% endfor %}

        {{ photo_formset.management_form }}
        {% for form in photo_formset %}
            {% include 'form.html' %}
        {% endfor %}

        <div class="form-group">
            <input type="submit" class="btn btn-info form-control" value="{{ submit_text }}">
        </div>
    </form>
    </div>
{% endblock content %}

company/templates/company/company_list.html
{% extends 'base.html' %}
{% load thumbnail i18n %}

{% block content %}
  <div class="row">
    {% for chunk in categories %}
      <div class="col-md-4">
        <ul class="category">
          {% for category in chunk %}
            <li>
              <a href="{% url 'companies:category' category.slug %}"
                 class="{% if category.slug == active_category %}active{% endif %}">
                {{ category }}
              </a>
            </li>
          {% endfor %}
        </ul>
      </div>
    {% endfor %}
  </div>

  {% if request.user.is_authenticated %}
    <div class="col-md-12">
      <a href="{% url 'companies:register' %}" class="pull-right btn btn-info mb15">
        {% trans 'Register new company' %}
      </a>
    </div>
  {% endif %}

  <div class="companies">
    {% for company in companies_list %}
      {% cycle '<div class="clearfix">' '' '' %}
        <div class="company col-md-4 text-center">
          <div class="img-wrapper box">
            <div class="content">
              <img src="{% thumbnail company.logo 160x160 crop %}"
                   alt="{{company.name}}"
                   class="img-responsive">
              {% if created_by_user %}
                <div class="crud-company">
                  <a href="{% url 'companies:update' pk=company.id %}">
                    <span class="glyphicon glyphicon-pencil"></span>
                  </a>
                  <a href="{% url 'companies:delete' pk=company.id %}">
                    <span class="glyphicon glyphicon-remove"></span>
                  </a>
                </div>
              {% endif %}
            </div>
          </div>
          <a href="{% url 'companies:detail' pk=company.id %}">
            {{company.name}}
          </a>
          <div class="description">{{ company.overview|truncatewords:10 }}</div>
        </div>
      {% cycle '' '' '</div>' %}
    {% empty %}
      <div class="text-center">{% trans 'No business found by search.' %}</div>
    {% endfor %}
  </div>
{% endblock content %}

company/templates/company/gallery.html
{% load thumbnail %}
    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        {% for photo in gallery %}
          <li data-target="#carousel-example-generic"
              data-slide-to="{{ forloop.counter0 }}"
              class="{% if forloop.first %}active{% endif %}"></li>
        {% endfor %}
      </ol>

      <!-- Wrapper for slides -->
      <div class="carousel-inner" role="listbox">
        {% for photo in gallery %}
            <div class="item{% if forloop.first %} active{% endif %}">
              <img src="{% thumbnail photo.image 700x500 crop %}" alt="{{ photo }}" width=100%>
              <div class="carousel-caption">
                <h3>{{ photo.product }}</h3>
              </div>
            </div>
        {% endfor %}
      </div>

      <!-- Controls -->
      <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>

company/templates/company/plugin.html
<script type="text/javascript"
        src="{{ STATIC_URL }}django_ajax/js/jquery.ajax.min.js">
</script>
<script type="text/javascript">
    function sentAjax(url) {
        ajaxGet(url, function(content) {
            var gallery = document.getElementById('gallery-slider');
            gallery.innerHTML = content;
        })
        return false
    }
    sentAjax('{% url 'companies:full_gallery' %}')
</script>
<div class="row">
	{% for chunk in categories %}
		<div class="col-md-4">
			<ul class="category">
				{% for category in chunk %}
					<li>
						<a href="#" onclick="return sentAjax('{% url 'companies:gallery' category.id %}')">{{ category }}</a>
					</li>
				{% endfor %}
			</ul> 
		</div> 
	{% endfor %}
</div>
<div id="gallery-slider">
    {% include 'company/gallery.html' %}
</div>